version: '3'

services:
  app:
    depends_on:
      - 'postgres'
    image: 'vbarrier/motoradmin:latest'
    ports:
      - '3000:3000'
    volumes:
      - ./motor-admin/app:/app
      - ./motor-admin/config/database.yml:/opt/motor-admin/config/database.yml:ro
      #- ./motor-admin/modules/databaseName:/opt/motor-admin/app/models/databaseName:ro #add your modules models for other databases
    environment:
      SECRET_KEY_BASE:

  postgres:
    image: 'postgres:17.4'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: motoradmin

  pgadmin:
    depends_on:
      - 'postgres'
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: #edit#
      PGADMIN_DEFAULT_PASSWORD: #edit#
    volumes:
      - ./motor-admin/pgadmin:/var/lib/pgadmin

volumes:
  postgres:
